name: jewellery
description: "Task Mangement Application"

publish_to: "none" # Remove this line if you wish to publish to pub.dev


version: 1.0.3+4

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  shared_preferences: ^2.2.0
  intl: ^0.18.1
  curl_logger_dio_interceptor: ^1.0.0
  http_parser: ^4.0.2
  provider: ^6.1.2
  cached_network_image: ^3.2.3
  http: ^1.1.0
  shimmer: ^3.0.0

  url_launcher:
  image_picker: ^0.8.4+4
  dotted_border: ^2.1.0
  get:
  fluttertoast: ^8.2.8
  get_storage: ^2.1.1
  dropdown_button2: ^2.3.9
  meta:

dev_dependencies:
  flutter_test:
    sdk: flutter



  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/


  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400

